language: python

dist: xenial

python:
  - "3.5"
  #- "3.6"
  #- "3.7"
  #- "pypy"

env:
  - DJANGO_VERSION="2.2"
  #- DJANGO_VERSION="3.0.7"
  #- DJANGO_VERSION="1.6"
  #- DJANGO_VERSION="1.7"

install:
  #- pip install "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
  
  #- pip install -r requirements.txt

  - pip3 install "Django==${DJANGO_VERSION}"
  - pip3 install Sphinx


#script: python manage.py test drip
script:
  - python manage.py makemigrations drip
  - python manage.py makemigrations credits
  - python manage.py makemigrations auth
  - python manage.py migrate
  - python manage.py test
